### ISSUE TITLE
No hay resultados en la búsqueda de vuelos

### ISSUE THREAD

**Issue by ellopc** [ellopc/agencia-viajes-web#2]
Durante la integración del sistema de búsqueda de vuelos, he notado que al intentar buscar vuelos en la pagina web, aparece un mensaje de error indicando que no se encontraron resultados, a pesar de haber vuelos registrados en la base de datos.

Mensaje de error: **The requested resource [Ejemplo de prueba en búsqueda de vuelos] was not found on this server.**

Posibles soluciones:

- Verificar la Conexión a la Base de Datos: Asegurarse de que la conexión a la base de datos se establece correctamente en `scripts/buscar_vuelos.php`.
- Revisar la Consulta SQL: Comprobar que la consulta SQL en `scripts/buscar_vuelos.php` está correctamente formulada y que los parámetros se están pasando correctamente.
- Validar Datos de Entrada: Asegurarse de que los datos de entrada del formulario de búsqueda son válidos y coinciden con los registros de la base de datos.

**Comment by Ignaciopz** [comment]
El error recibido indica que el servidor no puede encontrar el archivo buscar_vuelos.php en la ubicación esperada. Esto puede deberse a varias razones, como una estructura de carpetas incorrecta o rutas de archivo mal configuradas en tu código. Específicamente podemos encontrar un error en el archivo "formularios.php" en la linea de código 30 
"form action="../scripts/buscar_vuelos.php" method="get""
hay un problema en la ruta indicada en esta linea, la cual podemos solucionar eliminando "../", quedando de la siguiente manera 
"form action="scripts/buscar_vuelos.php" method="get""

esto ya nos proporcionaria los resultados de busqueda que esperamos:
![image](https://github.com/user-attachments/assets/0f7de24d-d7a7-46db-92ba-541261f526e8)

**Comment by Ignaciopz** [comment]
El error que esta recibiendo indica que el servidor no puede encontrar el archivo buscar_vuelos.php en la ubicación esperada. Esto puede deberse a varias razones, como una estructura de carpetas incorrecta o rutas de archivo mal configuradas en tu código. Específicamente podemos encontrar un error en el archivo "formularios.php" en la linea de código 30 
"<form action="../scripts/buscar_vuelos.php" method="get">", hay un problema en la ruta indicada en esta linea, la cual podemos solucionar eliminando "../", quedando de la siguiente manera "<form action="scripts/buscar_vuelos.php" method="get">"
